// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class QuestionComment
{
    public int Id { get; set; }

    public int QuestionId { get; set; }

    public string Comment { get; set; }

    public virtual Question Question { get; set; }
}