// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Question
{
    public int QuestionId { get; set; }

    public int QuestionnaireId { get; set; }

    public int QuestionType { get; set; }

    public string QuestionHeader { get; set; }

    public virtual ICollection<QuestionComment> QuestionComments { get; set; } = new List<QuestionComment>();

    public virtual ICollection<QuestionImage> QuestionImages { get; set; } = new List<QuestionImage>();

    public virtual ICollection<QuestionOption> QuestionOptions { get; set; } = new List<QuestionOption>();

    public virtual QuestionType QuestionTypeNavigation { get; set; }

    public virtual Questionnaire Questionnaire { get; set; }
}