// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Questionnaire
{
    public int QuestionnaireId { get; set; }

    public int Department { get; set; }

    public DateOnly? QuestionnaireCreatedDate { get; set; }

    public int UserId { get; set; }

    public virtual Department DepartmentNavigation { get; set; }

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    public virtual User User { get; set; }

    public virtual ICollection<Branch> Branches { get; set; } = new List<Branch>();

}