// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class User
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string UserPassword { get; set; }

    public string UserPhone { get; set; }

    public int UserGroup { get; set; }

    public int UserDepartment { get; set; }

    public virtual ICollection<Questionnaire> Questionnaires { get; set; } = new List<Questionnaire>();

    public virtual Department UserDepartmentNavigation { get; set; }

    public virtual UserGroup UserGroupNavigation { get; set; }
}